"""add relation posts

Revision ID: 392408eb0673
Revises: 1d754b36716e
Create Date: 2020-06-13 10:59:41.875217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '392408eb0673'
down_revision = '1d754b36716e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('posted', sa.DateTime(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    # ### end Alembic commands ###
