"""add post_pic_path column to posts table

Revision ID: 3d10866e087c
Revises: 68224e914592
Create Date: 2020-06-14 17:53:53.878485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d10866e087c'
down_revision = '68224e914592'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('post_pic_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'post_pic_path')
    # ### end Alembic commands ###
