"""add columns to admins table

Revision ID: 68224e914592
Revises: c8d701f4358b
Create Date: 2020-06-14 11:43:21.275095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68224e914592'
down_revision = 'c8d701f4358b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('bio', sa.String(), nullable=True))
    op.add_column('admins', sa.Column('name', sa.String(), nullable=True))
    op.add_column('admins', sa.Column('prof_pic_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admins', 'prof_pic_path')
    op.drop_column('admins', 'name')
    op.drop_column('admins', 'bio')
    # ### end Alembic commands ###
